tap "jandedobbeleer/oh-my-posh"

brew "zsh"
brew "git"
brew "stow"
brew "fnm"
brew "uv"
brew "neovim"
brew "tmux"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "zoxide"
brew "eza"
brew "bat"
brew "jq"
brew "lazygit"
brew "oh-my-posh"

# Plugins Zsh (Común)
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# --- SOLO MACOS (Casks & Apps Gráficas) ---
if OS.mac?
    cask "alacritty"
    # Las fuentes ahora se instalan directamente como casks normales
    cask "font-iosevka-nerd-font"
    cask "docker"
end

# --- SOLO LINUX ---
if OS.linux?
    brew "gcc"
end